<?php
?>

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="Model/Skin/css/style.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
        <title>KV CSV Dashboard</title>
    </head>
    <body>
        <?php require_once "View/html/header.phtml" ?>
       
     <div class="container">
        <div class="dashboard">
            <div class="card">
                <!-- <a href="export_orders.html"> -->
                <a href="<?php echo $this->getUrl('index', 'export') ?>">
                    <i class="fas fa-file-export"></i>
                    <h3>Export CSV</h3>
                    <p>Export Magento Order Data to CSV</p>
                </a>
            </div>
            <div class="card">
                <!-- <a href="custom_export.html"> -->
                <a href="<?php echo $this->getUrl('index', 'custom_export') ?>">
                    <i class="fas fa-file-alt"></i>
                    <h3>Custom Export</h3>
                    <p>Export Custom Query Data to CSV</p>
                </a>
            </div>
            <div class="card">
                <!-- <a href="compare.html"> -->
                <a href="<?php echo $this->getUrl('index', 'compare') ?>">
                    <i class="fas fa-file-csv"></i>
                    <h3>Compare CSV</h3>
                    <p>Compare Two CSV Files</p>
                </a>
            </div>
            <div class="card">
                <!-- <a href="upload.html"> -->
                <a href="<?php echo $this->getUrl('index', 'upload') ?>">
                    <i class="fas fa-upload"></i>
                    <h3>Upload CSV</h3>
                    <p>Upload a CSV File</p>
                </a>
            </div>
            <div class="card">
                <!-- <a href="download.html"> -->
                <a href="<?php echo $this->getUrl('index', 'download') ?>">
                    <i class="fas fa-download"></i>
                    <h3>Download CSV</h3>
                    <p>View and Download CSV Files</p>
                </a>
            </div>
        </div>
    <?php require_once "View/html/footer.phtml" ?>
</body>
</html>